### ISSUE TITLE
Instance not stopped running service if ensure=>absent

### ISSUE THREAD

**Issue by toepi** [camptocamp/puppet-tomcat#100]
If you set ensure to absent for tomcat::instance, puppet doesn't stop the service, it only remove the init-script. I think this is the problem, because it delete init-script before stopping instance.

I have made following changes:
--- a/puppet/modules/tomcat/manifests/instance.pp
+++ b/puppet/modules/tomcat/manifests/instance.pp
@@ -556,7 +556,14 @@ define tomcat::instance(
       installed => false,
       absent    => false,
     },
-    require => [File["/etc/init.d/tomcat-${name}"], $servicerequire],
+    require => $ensure ? {
+      absent  => [$servicerequire],
+      default => [File["/etc/init.d/tomcat-${name}"], $servicerequire],
+    },
+    before  => $ensure ? {
+      absent  => File["/etc/init.d/tomcat-${name}"],
+      default => undef,
+    },
     pattern => "-Dcatalina.base=${tomcat::instance_basedir}/${name}",
   }
and it seem to work like expected.

**Comment by mcanevet** [comment]
@toepi could please you provide a PR for that?

**Comment by toepi** [comment]
@mcanevet will give my best.

I found this issue while evaluate puppet at work, but we decided against it, so I must search the old code to reproduce it. Then you completly rewritten this part. It is unclear if still present.
