### ISSUE TITLE
logrotate template should include owner / group

### ISSUE THREAD

**Issue by sopeters** [camptocamp/puppet-tomcat#101]
logrotate.catalina.erb should be as below:

# file installed but NOT managed by Puppet
<%= @basedir %>/logs/catalina.out {
      copytruncate
      weekly
      size 500M
      dateext
      rotate 53
      compress
      delaycompress
      missingok
      create 644 <%= @owner %> <%= @group %>
}

**Comment by mcanevet** [comment]
No answer for months, I close this issue
