### ISSUE TITLE
service file dont work anymore (rhel7.0 -> rhel 7.1)

### ISSUE THREAD

**Issue by mremy** [camptocamp/puppet-tomcat#128]
The file:
https://github.com/camptocamp/puppet-tomcat/blob/master/manifests/instance/config.pp#L216
is not updated if the source change:
https://github.com/camptocamp/puppet-tomcat/blob/master/manifests/instance/config.pp#L221

Between rehl7.0 and rhel7.1, the file /usr/lib/systemd/system/tomcat.service is updated, and the one from rhel7.0 don't work anymore.

Workaround:
 -remove  "/usr/lib/systemd/system/tomcat-${name}.service"
 -launch puppet, and the file is created ok

It seems not that easy to handle this case with "file".

**Comment by mremy** [comment]
Workaround work only to re-create the service file.
But the service script don't works, as the script changed a lot.
Deeper refactoring/investigation needed.

**Comment by mremy** [comment]
The service file is generated like this (partial,here  with a tomcat1 instance):
[Service]
Type=simple
EnvironmentFile=/etc/tomcat/tomcat.conf
Environment="SERVICE_NAME=tomcat-tomcat1"
EnvironmentFile=-/etc/sysconfig/tomcat
ExecStart=/usr/libexec/tomcat/server start
ExecStop=/usr/libexec/tomcat/server stop

And the line:
EnvironmentFile=-/etc/sysconfig/tomcat
Should be:
EnvironmentFile=-/etc/sysconfig/tomcat-tomcat1

**Comment by mcanevet** [comment]
@mremy I'm wordering if there is not another way to do it with systemd?
Isn't there a way to override service file in /etc/systemd/something?

**Comment by mremy** [comment]
@mcanevet: I don't know, but it seems a good idea to base our script on the redhat one (as it's done).
I just hope it won't change on every minor-release...
The "/etc/sysconfig/tomcat-tomcat1" is already created by our  receipt.

**Comment by mremy** [comment]
Fixed by: https://github.com/camptocamp/puppet-tomcat/pull/129
