### ISSUE TITLE
Unable to set "nofile" limit before starting tomcat instance

### ISSUE THREAD

**Issue by dankristensen** [camptocamp/puppet-tomcat#130]
Under debian it is not possible to set the number of allowed open files before starting the specific tomcat instance:

In this file: tomcat.init.erb it is not possible to inject any code before: 
$SU <%= @owner %> -c "umask <%= @umask %>; $CATALINA_HOME/bin/catalina.sh start" > /dev/null

Are there any other approaches for increasing the number of open files on this platform?

**Comment by mcanevet** [comment]
@dankristensen you should use `tomcat::ulimit`.
