### ISSUE TITLE
puppet-tomcat 

### ISSUE THREAD

**Issue by rohitbharti275** [camptocamp/puppet-tomcat#161]
Hi ,

I have cloned this and it got created in my /etc/puppet/modules/puppet-tomcat and now i have changed my site.pp under /etc/puppet/manifests/site.pp to
```puppet
node default {
class { 'tomcat':
      version     => 6,
      sources     => true,
      sources_src => 'http://archive.apache.org/dist/tomcat/',
    }
}
```

i am getting syntax error while doing so please refer the screen shot below i have only modified the site.pp residing at /etc/puppet/manifests/site.pp and my puppet-tomcat  module is under /etc/puppet/modules/puppet-tomcat.
I am running puppet agent -t on my puppetagent following is the error
![tomcaterror](https://user-images.githubusercontent.com/30049205/28022615-50015598-65a9-11e7-8ce0-b4d628842a09.PNG)

**Comment by rohitbharti275** [comment]
Hi Request you to look into this

**Comment by mcanevet** [comment]
Could you try to rename `/etc/puppet/modules/puppet-tomcat` to `/etc/puppet/modules/tomcat`?
Pupper autoloading can not work if you name the directory `puppet-tomcat`.

**Comment by rohitbharti275** [comment]
Hi,

I renamed it to /etc/puppet/modules/tomcat and my site.pp under /etc/puppet/manifests/site.pp
contains 
node default {
class { 'tomcat':
version => 6,
sources => true,
sources_src => 'http://archive.apache.org/dist/tomcat/',
}
}
![tomcat](https://user-images.githubusercontent.com/30049205/28062500-c34e00c6-664b-11e7-88dd-bedd6760c26a.PNG)

**Comment by rohitbharti275** [comment]
still i am getting the error

**Comment by mcanevet** [comment]
It looks like you don't have puppetlabs-stdlib, did you get all dependencies?

**Comment by rohitbharti275** [comment]
dependencies? like I have cloned folder from github directly so do i need to install some dependencies apart from what I got from github

**Comment by mcanevet** [comment]
Do you known anything about Puppet and Puppet modules?
If no, I suggest you to look into that first. I really think your problem is not getting this module work, but more getting you Puppet repository set up.
I'm closing this for now, feel free to reopen if you really find a problem with this module.

**Comment by rohitbharti275** [comment]
Hi I do have puppetlabs-stdlib under /etc/puppet/modules/stdlib. Please refer the screenshot
![stdlib](https://user-images.githubusercontent.com/30049205/28068414-1118a632-6663-11e7-8b06-81b6e2a03ec9.PNG)

**Comment by rohitbharti275** [comment]
Yes I have installed sample packages using puppet copying files and editing files now when i am trying to use this module for installing Tomcat i am facing the issue because I do have stdlib under my /etc/puppet/modules/stdlib same location where my tomcat module is

**Comment by mcanevet** [comment]
The error message stating that `validate_re` is not available let me think that you have either a problem in your puppet setup or you don't have the proper version of `puppetlabs-stdlib` as this function is part of this package.
In any case the problem comes from this module per se.

**Comment by rohitbharti275** [comment]
Ok, Thanks for your quick response I am a beginner in puppet and want to explore more so i have changed my /etc/puppet/manifests/site.pp as 
node default {
class { 'tomcat':
       version     => 6,
       sources     => true,
       sources_src => 'http://archive.apache.org/dist/tomcat/',
    }
}
means i am keeping my site.pp under /etc/puppet/manifests/site.pp and my module is under /etc/puppet/modules/tomcat and when I run /etc/puppet/manifests/site.pp using puppet agent -t from my agent i get the different error now please refer the screen shot
![err](https://user-images.githubusercontent.com/30049205/28070150-8f3f2292-6669-11e7-9623-a36eb4cad1ac.PNG)

Here I am completely clueless so seeking your support what i might be doing wrong because puppet version i am using is 3.4.3 and after reading from /etc/puppet/modules/tomcat/README am following the steps and changing the /etc/puppet/manifests/site.pp and execute it on agent

**Comment by mcanevet** [comment]
Again, a problem in your setup, you don't have all the dependencies for this module.
Here the error message is quite explicit about that it can't find the `archive::download` resource type which is in one of the dependencies of this module.
I really suggest you to learn a little bit about Puppet...
Your (current) problem is definitely not due to a bug in this module.
