### ISSUE TITLE
issue running tomcat

### ISSUE THREAD

**Issue by rohitbharti275** [camptocamp/puppet-tomcat#162]
Hi 
Yes I have installed sample packages using puppet copying files and editing files now when i am trying to use this module for installing Tomcat i am facing the issue because I do have stdlib under my /etc/puppet/modules/stdlib same location where my tomcat module is
![stdlib](https://user-images.githubusercontent.com/30049205/28068661-1c9e3a98-6664-11e7-9f9d-43d093a7df36.PNG)

**Comment by mcanevet** [comment]
Are you kidding me?
See. https://github.com/camptocamp/puppet-tomcat/issues/161
Again, this is not an issue with this module, you obviously lack the dependencies.
Please read the Puppet documentation on how to install a Puppet module.
